### ISSUE TITLE
APIError(code=-1021): Timestamp for this request is outside of the recvWindow

### ISSUE THREAD

**Issue by edoreld** [salimane/cryptodiversify#5]
When I run `python3 hodl.py`, i get:

```
[2022-03-10 11:06:22,532][      MainThread][   bot][    INFO] Starting CryptoDiversify...
APIError(code=-1021): Timestamp for this request is outside of the recvWindow.
```

I found [this Issue](https://github.com/ccxt/ccxt/issues/936) that might be useful in debugging the problem. 

Thanks in advance.

**Comment by salimane** [comment]
Hmm, … did you make sure your machine's clock is synched with a Time Server like `pool.ntp.org` or `time.apple.com` ?

**Comment by edoreld** [comment]
I figured out the problem. I'm using Ubuntu with WSL (Windows Subsystem for Linux), and for some reason the date there wasn't the right one. I ran  `sudo ntpdate pool.ntp.org` to update the time and then ran the script again. This time, it worked flawlessly.
